"""Pydantic models for the Phase 7 reporting system."""

from __future__ import annotations

from enum import StrEnum
from pathlib import Path
from typing import Any

from pydantic import BaseModel, Field


class ReportType(StrEnum):
    """Publication report kinds."""

    EXECUTIVE = "executive"
    TECHNICAL = "technical"
    EXPERIMENT = "experiment"
    AGENT_COMPARISON = "agent_comparison"
    METRIC = "metric"
    TASK_ANALYSIS = "task_analysis"
    REGRESSION = "regression"
    CI_SUMMARY = "ci_summary"


class SectionId(StrEnum):
    """Canonical report section identifiers."""

    EXPERIMENT_METADATA = "experiment_metadata"
    DATASET_SUMMARY = "dataset_summary"
    AGENT_CONFIGURATION = "agent_configuration"
    BENCHMARK_CONFIGURATION = "benchmark_configuration"
    EVALUATION_METHODOLOGY = "evaluation_methodology"
    OVERALL_RESULTS = "overall_results"
    METRIC_BREAKDOWN = "metric_breakdown"
    CATEGORY_SCORES = "category_scores"
    TASK_PERFORMANCE = "task_performance"
    FAILURE_ANALYSIS = "failure_analysis"
    TRAJECTORY_SUMMARY = "trajectory_summary"
    TOOL_USAGE_SUMMARY = "tool_usage_summary"
    LATENCY = "latency"
    COST = "cost"
    CONFIDENCE = "confidence"
    WARNINGS = "warnings"
    RECOMMENDATIONS = "recommendations"
    APPENDIX = "appendix"
    DIFF = "diff"
    REGRESSIONS = "regressions"


class BrandConfig(BaseModel):
    """Future-facing branding knobs for templates."""

    product_name: str = "GitHubBench-Delta"
    logo_path: str | None = None
    primary_color: str = "#1a365d"
    secondary_color: str = "#2c5282"
    footer_text: str = "Generated by GitHubBench-Delta reporting"


class ReportRequest(BaseModel):
    """User/CLI request to build one or more report artifacts."""

    experiment_ids: list[str] = Field(default_factory=list)
    report_type: ReportType = ReportType.TECHNICAL
    formats: list[str] = Field(default_factory=lambda: ["markdown"])
    output_dir: Path | None = None
    template_dir: Path | None = None
    brand: BrandConfig = Field(default_factory=BrandConfig)
    baseline_id: str | None = None
    candidate_id: str | None = None
    agent_id: str | None = None
    dataset_version: str | None = None
    prompt_version: str | None = None
    results_dir: Path | None = None
    sqlite_path: Path | None = None


class SectionPayload(BaseModel):
    """Rendered section content for templates and exporters."""

    id: str
    title: str
    summary: str = ""
    tables: list[dict[str, Any]] = Field(default_factory=list)
    stats: dict[str, Any] = Field(default_factory=dict)
    notes: list[str] = Field(default_factory=list)
    chart_ids: list[str] = Field(default_factory=list)


class ChartAsset(BaseModel):
    """Plotly figure + optional static image for PDF/Markdown."""

    chart_id: str
    title: str
    plotly_json: dict[str, Any] = Field(default_factory=dict)
    png_relpath: str | None = None
    png_base64: str | None = None


class MetricDelta(BaseModel):
    key: str
    baseline: float | None = None
    candidate: float | None = None
    delta: float | None = None
    relative: float | None = None
    is_regression: bool = False


class DiffResult(BaseModel):
    """Structured comparison between two experiment (or filter) scopes."""

    baseline_id: str
    candidate_id: str
    compare_kind: str = "experiment"
    notes: list[str] = Field(default_factory=list)
    overall_delta: MetricDelta | None = None
    metric_deltas: list[MetricDelta] = Field(default_factory=list)
    group_deltas: list[MetricDelta] = Field(default_factory=list)
    task_deltas: list[MetricDelta] = Field(default_factory=list)
    cost_delta: MetricDelta | None = None
    latency_delta: MetricDelta | None = None
    trajectory_deltas: list[MetricDelta] = Field(default_factory=list)
    dataset_version_baseline: str | None = None
    dataset_version_candidate: str | None = None
    prompt_version_baseline: str | None = None
    prompt_version_candidate: str | None = None
    agent_baseline: str | None = None
    agent_candidate: str | None = None


class ReportDocument(BaseModel):
    """Structured report payload consumed by all exporters."""

    report_type: ReportType
    title: str
    experiment_ids: list[str] = Field(default_factory=list)
    generated_at: str = ""
    brand: BrandConfig = Field(default_factory=BrandConfig)
    sections: list[SectionPayload] = Field(default_factory=list)
    charts: dict[str, ChartAsset] = Field(default_factory=dict)
    recommendations: list[str] = Field(default_factory=list)
    warnings: list[str] = Field(default_factory=list)
    leaderboard: list[dict[str, Any]] = Field(default_factory=list)
    evaluations: list[dict[str, Any]] = Field(default_factory=list)
    tasks: list[dict[str, Any]] = Field(default_factory=list)
    metric_stats: list[dict[str, Any]] = Field(default_factory=list)
    category_scores: dict[str, float] = Field(default_factory=dict)
    overview: dict[str, Any] = Field(default_factory=dict)
    experiment_detail: dict[str, Any] = Field(default_factory=dict)
    diff: DiffResult | None = None
    appendix: dict[str, Any] = Field(default_factory=dict)
    metadata: dict[str, Any] = Field(default_factory=dict)
